### ISSUE TITLE
Validar que esta nueva versión implementa las funcionalidades y los estándares de código definidos

### ISSUE THREAD

**Issue by zeittgeist** [macias-laverde-trabajo-grado/GestionCurricularBackend#7]
Validar que esta nueva versión implementa las funcionalidades y los estándares de código definidos, a través de la medición de complejidad cognitiva, la complejidad computacional y el cumplimiento de los requerimientos funcionales de los componentes web y los servicios relacionados a los módulos en cuestión.

- [ ] https://github.com/macias-laverde-trabajo-grado/GestionCurricularBackend/issues/23
- [ ] https://github.com/macias-laverde-trabajo-grado/GestionCurricularBackend/issues/24
- [ ] https://github.com/macias-laverde-trabajo-grado/GestionCurricularBackend/issues/26
- [ ] https://github.com/macias-laverde-trabajo-grado/GestionCurricularBackend/issues/27
